# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PAhRPLyMqtSHbc2wtQixGYoR2f5ycjiV
"""

input_path = "/content/drive/MyDrive/CSE221inputs/Lab1/Task3/input3.txt"
input = open(input_path, "r")
lst = input.readlines()
id_lst = lst[1].split()
marks_lst = lst[2].split()
txt = ''

id_lst = [int(id_str) for id_str in id_lst]
marks_lst = [int(marks_str) for marks_str in marks_lst]

def bubbleSort(marks_lst, id_lsts):
    for i in range(len(marks_lst)-1):
        checker = False
        for j in range(len(marks_lst)-i-1):
            if marks_lst[j] < marks_lst[j+1]:
                marks_lst[j], marks_lst[j+1] = marks_lst[j+1], marks_lst[j]
                id_lsts[j], id_lsts[j+1] = id_lsts[j+1], id_lsts[j]
                checker = True
            elif marks_lst[j] == marks_lst[j+1] and id_lsts[j] > id_lsts[j+1]:
                id_lsts[j], id_lsts[j+1] = id_lsts[j+1], id_lsts[j]
                checker = True
        if not checker:
            break
final_lst = bubbleSort(marks_lst,id_lst)

for i in range(len(id_lst)):
    txt += f'id_lst: {id_lst[i]} Mark: {marks_lst[i]}\n'

output_path = "/content/drive/MyDrive/CSE221inputs/Lab1/Task3/output3.txt"
output = open(output_path, "w")
output.writelines(txt)
output.close()