# -*- coding: utf-8 -*-
"""Lab1_Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-NREgHx5BYgy4pndo27RLlYukbkvFbP
"""

path = "/content/drive/MyDrive/CSE221inputs/Lab1/Task2/input1.txt"
input1 = open(path, "r")
lst = input1.readlines()
lst_sort = lst[1].split()
print(lst_sort)
txt = ""
arr = []
for i in lst_sort:
    arr.append(int(i))
def bubbleSort(arr):
    for i in range(len(arr)-1):
        checker = False
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                checker = True
        if checker == False:
            break
bubble = bubbleSort(arr)
for i in arr:
    txt += str(i) + " "
path2 = "/content/drive/MyDrive/CSE221inputs/Lab1/Task2/output1.txt"
output = open(path2,"w")
output.writelines(txt)
output.close()