# -*- coding: utf-8 -*-
"""CSE221_Lab1_Task1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tul8Qb73Aaptc60qbbxnOlsJnLn-XGJh
"""

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/CSE221inputs/Lab1/Task1/inp1.txt'
input1 = open(path, "r")
lst = input1.readlines()
txt = ""
for i in lst[1:len(lst)]:
  if int(i)%2 == 0:
    txt = txt + f"{int(i)} is an Even number." + "\n"
  else:
    txt = txt + f"{int(i)} is an Odd number. " + "\n"

path1 = "/content/drive/MyDrive/CSE221inputs/Lab1/Task1/out1.txt "
out1 = open(path1, "w")
out1.writelines(txt)
out1.close()